version: "3.9"
services:
  firebase-emulator:
    container_name: firebase-emulator.cxcxc
    build:
      context: .
      dockerfile: Dockerfile
    image: "cxcxc/flutterfire_emulator"
    ports:
      - "9099:9099"
      - "9005:9005"
      - "8085:8085"
      - "8080:8080"
      - "5001:5001"
      # - "5000:5000"
      - "4000:4000"
      - "9199:9199"
      - "4400:4400"
      - "4500:4500"
    tty: true
    volumes:
      - .:/home/node
