// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTrk_evbm_V2XocW6Vbq5VLVafGzLmfPs',
    appId: '1:237291771385:web:0998ba951ba00afba21928',
    messagingSenderId: '237291771385',
    projectId: 'flutterfire-ui-codelab-9bfc9',
    authDomain: 'flutterfire-ui-codelab-9bfc9.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-9bfc9.appspot.com',
    measurementId: 'G-226F49JCJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX3gX2aSdJQkZfZZlKDAQtOTCMuwQxx84',
    appId: '1:237291771385:android:91bb09d1f5f2d30ba21928',
    messagingSenderId: '237291771385',
    projectId: 'flutterfire-ui-codelab-9bfc9',
    storageBucket: 'flutterfire-ui-codelab-9bfc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9KAQJOeC23fMefALQZ2gdBRpmXIgsMJU',
    appId: '1:237291771385:ios:185aeb0b97003b9fa21928',
    messagingSenderId: '237291771385',
    projectId: 'flutterfire-ui-codelab-9bfc9',
    storageBucket: 'flutterfire-ui-codelab-9bfc9.appspot.com',
    androidClientId: '237291771385-n3e4b4f950l7q3rgqk6mmdhit5d3d7o1.apps.googleusercontent.com',
    iosClientId: '237291771385-4fp98lm3kmch74bjficj8ukofm2i693n.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
